# Generated by Django 6.0.2 on 2026-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location_city', models.CharField(max_length=255)),
                ('location_state', models.CharField(blank=True, max_length=255, null=True)),
                ('location_country', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Remote', 'Remote'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=50)),
                ('job_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('skills_required', models.CharField(max_length=250)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'indexes': [models.Index(fields=['job_title'], name='company_job_job_tit_987c9d_idx'), models.Index(fields=['company_name'], name='company_job_company_a3707f_idx'), models.Index(fields=['location_city'], name='company_job_locatio_3b74f3_idx')],
            },
        ),
    ]
