# Generated by Django 5.2.9 on 2026-03-22 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_job_posted_by_companyprofile_job_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior', 'Senior'), ('Executive', 'Executive'), ('Any', 'Any Experience Level')], db_index=True, default='Any', max_length=50),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='company_job_job_typ_aab04a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='company_job_experie_caeb76_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_status'], name='company_job_job_sta_62464d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-posting_date'], name='company_job_posting_8f31c0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='company_job_salary__6efc7e_idx'),
        ),
    ]
