# Generated by Django 5.2.9 on 2026-03-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Hospitality', 'Hospitality'), ('Media', 'Media'), ('Government', 'Government'), ('Other', 'Other')], db_index=True, max_length=100, null=True),
        ),
    ]
