# Generated by Django 6.0.2 on 2026-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'verbose_name': 'Candidate profile', 'verbose_name_plural': 'Candidate profiles'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job application', 'verbose_name_plural': 'Job applications'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(blank=True, help_text='e.g., LinkedIn, Referral', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['city'], name='user_candid_city_7b267f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['gender'], name='user_candid_gender_4f29d6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'candidate'], name='user_jobapp_job_id_9e2d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='user_jobapp_status_1b5427_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['created_at'], name='user_jobapp_created_c8f503_idx'),
        ),
    ]
