# Generated by Django 6.0 on 2026-03-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_job_posted_by_companyprofile_job_company_and_more'),
        ('user', '0003_candidateprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='application_resumes/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_match_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='user.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_candidates', to='company.job')),
            ],
            options={
                'verbose_name': 'Saved job',
                'verbose_name_plural': 'Saved jobs',
                'indexes': [models.Index(fields=['candidate', 'job'], name='user_savedj_candida_0a7b38_idx'), models.Index(fields=['created_at'], name='user_savedj_created_b2e416_idx')],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
