# Generated by Django 6.0.2 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_profile_options_alter_profile_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="profile_avatars/"),
        ),
    ]
