# Generated by Django 5.2.9 on 2026-03-16 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company / Employer')], db_index=True, default='candidate', help_text='User role determines access permissions and available features', max_length=20),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='core_profil_role_0122c2_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='core_profil_user_id_155486_idx'),
        ),
    ]
