# Generated by Django 5.2.9 on 2026-03-16 08:58

from django.db import migrations


def backfill_profile_roles(apps, schema_editor):
    """
    Backfill existing profile roles based on CompanyProfile existence.
    Users with CompanyProfile get 'company' role, others get 'candidate'.
    """
    Profile = apps.get_model('core', 'Profile')
    CompanyProfile = apps.get_model('company', 'CompanyProfile')
    
    # Get users with company profiles
    company_users = set(CompanyProfile.objects.values_list('user_id', flat=True))
    
    # Update all profiles
    for profile in Profile.objects.all():
        if profile.user_id in company_users or profile.user.posted_jobs.exists():
            profile.role = 'company'
        else:
            profile.role = 'candidate'
        profile.save(update_fields=['role'])


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - reset all roles to 'candidate' (default).
    """
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.all().update(role='candidate')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_role_profile_core_profil_role_0122c2_idx_and_more'),
        ('company', '0002_job_posted_by_companyprofile_job_company_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_profile_roles, reverse_backfill),
    ]
